//! Trait for chaining tuples together.
//!
//! The `ChainRight` trait allows concatenating two tuples into a single tuple.
//! This is primarily used internally to simplify type definitions in the
//! `TypedTuple` trait implementations.

/// Trait for chaining two tuples together.
///
/// This trait is implemented for all combinations of tuple sizes (up to 64
/// elements by default, or 128 with the `len_128` feature). It enables
/// type-level tuple concatenation and provides a method to concatenate tuple
/// values at runtime.
///
/// # Type Parameters
///
/// * `Other` - The tuple type to append to `Self`
///
/// # Examples
///
/// ```rust
/// # use typed_tuple::ChainRight;
/// // Type-level chaining
/// type Left = (u8, u16);
/// type Right = (u32, u64);
/// type Chained = <Left as ChainRight<Right>>::Output;
///
/// // Chained is equivalent to (u8, u16, u32, u64)
/// let _: Chained = (1u8, 2u16, 3u32, 4u64);
///
/// // Runtime chaining
/// let left = (1u8, 2u16);
/// let right = (3u32, 4u64);
/// let chained: Chained = left.chain_right(right);
/// assert_eq!(chained, (1u8, 2u16, 3u32, 4u64));
/// ```
pub trait ChainRight<Right> {
    /// The resulting tuple type after chaining `Self` with `Other`.
    type Output;

    /// Chains this tuple with another tuple, producing a single concatenated
    /// tuple.
    ///
    /// # Examples
    ///
    /// ```rust
    /// # use typed_tuple::ChainRight;
    /// let left = (1, 2, 3);
    /// let right = (4, 5);
    /// let result = left.chain_right(right);
    /// assert_eq!(result, (1, 2, 3, 4, 5));
    /// ```
    fn chain_right(self, right: Right) -> Self::Output;
}

/// Trait for chaining two tuples together on the left side.
///
/// This trait is implemented in terms of `ChainRight` to provide a convenient
/// way to chain tuples from the left side.
pub trait ChainLeft<Left> {
    /// The resulting tuple type after chaining `Left` with `Self`.
    type Output;

    /// Chains another tuple on the left side of this tuple, producing a single
    /// concatenated tuple.
    ///
    /// # Examples
    ///
    /// ```rust
    /// # use typed_tuple::ChainLeft;
    /// let left = (1, 2, 3);
    /// let right = (4, 5);
    /// let result = right.chain_left(left);
    /// assert_eq!(result, (1, 2, 3, 4, 5));
    /// ```
    fn chain_left(self, left: Left) -> Self::Output;
}

impl<Left, Right> ChainLeft<Left> for Right
where
    Left: ChainRight<Right>,
{
    type Output = Left::Output;

    fn chain_left(self, left: Left) -> Self::Output {
        left.chain_right(self)
    }
}

// The implementations are generated by the proc macro
typed_tuple_macros::generate_chain_right_impls!();
